### ISSUE TITLE
Example usage in the docs

### ISSUE THREAD

**Issue by tdeekens** [ben-leen/good-errors#4]
Thanks for the project. This is exactly what we would love to use in an Hapi based server. However we fail to see how to configure it. Currently our logging pipeline looks as

```js
const options = {
  ops: {
    interval: 1000,
  },
  reporters: {
    consoleReporter: [
      {
        module: 'good-squeeze',
        name: 'Squeeze',
        args: [{ log: '*', response: '*' }],
      },
      {
        module: 'good-errors',
      },
      {
        module: 'good-console',
      },
      'stdout',
    ],
  },
};
```

But get the error that `Failed to start server, shutting down! { AssertionError [ERR_ASSERTION]: Error in consoleReporter. good-errors must be a constructor function.`

Can you share what the problem is? Can we somehow add a example configuration to the readme?

**Comment by benleen** [comment]
Hey @tdeekens !

You should simple point to the `Errors` property via the `name` field on the configuration.
```
{
  module: 'good-errors',
  name: 'Errors'
},
```
I'll probably do a major release along with dependency updates and just have the root point to 'Errors' since I have no plan to add others. Meaning your config would become valid.

**Comment by tdeekens** [comment]
Cool. Thanks for the quick response! I will watch this space then.
